import express from 'express';
const router = express.Router();
import productRoutes from './products';
import customerRoutes from './customers';
import invoiceRoutes from './invoices';
import userRoutes from './users';
import useJournalRoutes from './journal';
import useDashboardRoutes from './dashboard';
import expenseRoutes from './expenses';
import reportRoutes from './reports';
import cashRoutes from './cash';
import cashOutRoutes from './cashOut';
import transportRoutes from './transport/';
import vatRoutes from './vat';

router.use('/products', productRoutes);
router.use('/customers', customerRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/users', userRoutes);
router.use('/journal', useJournalRoutes);
router.use('/dashboard', useDashboardRoutes);
router.use('/expenses', expenseRoutes);
router.use('/cash', cashRoutes);
router.use('/cashOut', cashOutRoutes);
router.use('/reports', reportRoutes);
router.use('/transport', transportRoutes);
router.use('/vat', vatRoutes);
export default router;
